services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    env_file:
      - .env.docker
    ports:
      - "8080:80" # Maps port 8080 on your host to port 80 in the container
    depends_on:
      - db
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
    networks:
      - laravel_network

  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    #   MYSQL_USER: ${DB_USERNAME}
    #   MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306" # Maps port 3307 on the host to port 3306 in the container
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  db_data:
